var annotated_dup =
[
    [ "arm_irq_regs_rpi3", "structarm__irq__regs__rpi3.html", null ],
    [ "arm_irq_regs_rpi4", "structarm__irq__regs__rpi4.html", null ],
    [ "AuxRegisters", "structAuxRegisters.html", null ],
    [ "CPUContext", "structCPUContext.html", null ],
    [ "DmaChannel", "structDmaChannel.html", null ],
    [ "DmaChannelRegs", "structDmaChannelRegs.html", null ],
    [ "DmaControlBlock", "structDmaControlBlock.html", null ],
    [ "GpioPinData", "structGpioPinData.html", null ],
    [ "GpioRegisters", "structGpioRegisters.html", null ],
    [ "I2CRegs", "structI2CRegs.html", null ],
    [ "MailboxClock", "structMailboxClock.html", null ],
    [ "MailboxFBBuffer", "structMailboxFBBuffer.html", null ],
    [ "MailboxFBDepth", "structMailboxFBDepth.html", null ],
    [ "MailboxFBPitch", "structMailboxFBPitch.html", null ],
    [ "MailboxFBRequest", "structMailboxFBRequest.html", null ],
    [ "MailboxFBSize", "structMailboxFBSize.html", null ],
    [ "MailboxGeneric", "structMailboxGeneric.html", null ],
    [ "MailboxPower", "structMailboxPower.html", null ],
    [ "MailboxRegisters", "structMailboxRegisters.html", null ],
    [ "MailboxSetPallete", "structMailboxSetPallete.html", null ],
    [ "MailboxTag", "structMailboxTag.html", null ],
    [ "Notif", "structNotif.html", null ],
    [ "Object", "structObject.html", null ],
    [ "PCMConfig", "structPCMConfig.html", null ],
    [ "PCMRegs", "structPCMRegs.html", null ],
    [ "Pipe", "structPipe.html", null ],
    [ "ProcessStateRegisters", "structProcessStateRegisters.html", null ],
    [ "PropertyBuffer", "structPropertyBuffer.html", null ],
    [ "Spi0Regs", "structSpi0Regs.html", null ],
    [ "Spinlock", "structSpinlock.html", "structSpinlock" ],
    [ "TaskBlock", "structTaskBlock.html", null ],
    [ "Timer", "structTimer.html", null ],
    [ "TimerRegisters", "structTimerRegisters.html", null ],
    [ "UartRegisters", "structUartRegisters.html", "structUartRegisters" ],
    [ "UartSettings", "structUartSettings.html", null ]
];